repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
      - id: check-added-large-files
      - id: check-ast
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
      - id: mypy
        args: [--config-file=src/configs/mypy.ini]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        language: system
        types: [file, python]
        entry: python3 -m pylint
        args: [--rcfile=src/configs/pylintrc]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

# Specify the files you want to include for the checks
exclude: '^$'  # Exclude empty filenames
